/*DESENVOLVIDO POR: RONALDO MAIA EM 30/03/17
OBJETIVO: PREENCHER O HISTÓRICO DA BAIXA DE TITULOS DO CONTAS A PAGAR E CONTAS A RECEBER*/
#include "rwmake.ch"

User Function HISTREC()

xReg := ALLTRIM(SE1->E1_CLIENTE)+"/"+ALLTRIM(SE1->E1_LOJA)+"-"+ ALLTRIM(SE1->E1_NOMCLI)

Return(xReg)

User Function HISTPAG()
	if ALLTRIM(SE2->E2_PREFIXO) == 'GPE'
		xReg := AllTrim(SE2->E2_HIST)
	else
		xReg := AllTrim(SE2->E2_FORNECE)+"/"+ALLTRIM(SE2->E2_LOJA)+"-"+ AllTrim(SE2->E2_NOMFOR)
	endif

Return(xReg)
